apiVersion: apps/v1
kind: Deployment
metadata:
  name: watermark-detection
spec:
  replicas: 3
  selector:
    matchLabels:
      app: watermark-detection
  template:
    metadata:
      labels:
        app: watermark-detection
    spec:
      containers:
      - name: watermark-detection
        image: your-docker-registry/watermark-detection:latest
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"